# Generated by Django 5.0.6 on 2024-06-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0002_remove_user_role_delete_role_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcat_id',
            new_name='subcat',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
